#!/bin/bash
# Rotate the server-to-server authentication keys held in Redis.
#
# GENERATED by setup/setup.sh from setup/worlds.conf. Re-run 'make setup' after
# adding a world rather than editing the world list here.
#
# ROTATION IS OVERLAPPING. Before a name's key is replaced, the value it is
# replacing is copied to server_auth_key:<name>:previous with a short TTL, and
# a world accepts either. Without that, the instant this script ran, a realm
# holding the value it read moments ago was refused -- and because the realm
# caches a key for a whole probe cycle, a rotation reliably landed inside one.
#
# ABSENCE IS AN OUTAGE. The realm refuses to start without
# server_auth_key:global, and a world with no key of its own refuses every
# realm handshake, which drops it off the world list with nothing said about
# why. This script exits non-zero if any key is missing after a run, so cron
# mail or a monitor notices. Check on it separately with --verify.
#
# Run from cron more often than the TTL:
#
#   0 3 * * * cd /path/to/mmo_server && bash common/server_keys/generate_daily_server_keys.sh
#
# Usage:
#   generate_daily_server_keys.sh            rotate every key
#   generate_daily_server_keys.sh --verify   check every key exists, change nothing
set -euo pipefail

REDIS_CLI=${REDIS_CLI:-redis-cli}
TTL=${SERVER_KEY_TTL:-86400}

# How long the key being replaced stays valid. Must be at least as long as the
# realm's world-probe cycle, and is capped well below the TTL so an old key
# never outlives the rotation that replaced it by much. Keep this in step with
# SERVER_KEY_OVERLAP_SECONDS in common/include/realm_world_auth.h.
OVERLAP=${SERVER_KEY_OVERLAP:-900}

VERIFY_ONLY=0
[ "${1:-}" = "--verify" ] && VERIFY_ONLY=1

MISSING=0
NAMES=()

set_key() {
    local name="$1"
    NAMES+=("$name")

    if [ "$VERIFY_ONLY" = 1 ]; then
        return 0
    fi

    # Keep the value being replaced usable for the overlap window. A peer that
    # read the old key seconds ago must still authenticate with it.
    local previous
    previous=$($REDIS_CLI GET "server_auth_key:$name" 2>/dev/null || true)
    if [ -n "$previous" ]; then
        $REDIS_CLI SETEX "server_auth_key:$name:previous" "$OVERLAP" "$previous" >/dev/null
    fi

    $REDIS_CLI SETEX "server_auth_key:$name" "$TTL" "$(openssl rand -hex 32)" >/dev/null
    echo "  rotated server_auth_key:$name"
}

# Fail loudly if a name ended up without a key. A silently missing key is the
# failure mode this whole script exists to prevent.
check_keys() {
    local name
    for name in "${NAMES[@]}"; do
        if [ "$($REDIS_CLI EXISTS "server_auth_key:$name")" != "1" ]; then
            echo "  MISSING server_auth_key:$name" >&2
            MISSING=$((MISSING + 1))
        fi
    done
}

if [ "$VERIFY_ONLY" = 1 ]; then
    echo "Verifying server auth keys (changing nothing)"
else
    echo "Rotating server auth keys (TTL ${TTL}s, previous key valid ${OVERLAP}s)"
fi

# The global key. The realm presents this to any world with no key of its own.
set_key global

# Per-world keys, from setup/worlds.conf.
set_key Armeia
set_key Bosteuis
set_key Cardinal
set_key Derive
set_key Exodus
set_key Prototype
set_key Karmel
set_key Longevity
set_key Nervow
set_key Jatrus

check_keys

echo
if [ "$MISSING" -ne 0 ]; then
    echo "FAILED: $MISSING key(s) missing. The realm will not start and any world"
    echo "        without a key will refuse every realm handshake." >&2
    exit 1
fi

if [ "$VERIFY_ONLY" = 1 ]; then
    echo "All ${#NAMES[@]} keys present."
else
    echo "Done. Keys expire in ${TTL}s; schedule this more often than that."
fi
